# Generated by Django 3.1.7 on 2021-05-28 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uchebnik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=32)),
                ('school_num', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=32)),
                ('teachers', models.ManyToManyField(blank=True, related_name='teachers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.SmallIntegerField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dnevnik.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='Нет темы.', max_length=32)),
                ('homework', models.CharField(default='Нет Д/З.', max_length=32)),
                ('lesson_begin', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('lesson_end', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('conference_link', models.CharField(blank=True, max_length=128)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('exercises', models.ManyToManyField(blank=True, to='uchebnik.Exercise')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnevnik.subject')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus_sym', models.CharField(max_length=1)),
                ('genus_num', models.SmallIntegerField(null=True)),
                ('tg_link', models.URLField(blank=True, null=True)),
                ('tg_chat_id', models.IntegerField(blank=True, null=True)),
                ('lessons', models.ManyToManyField(to='dnevnik.Lesson')),
                ('master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnevnik.school')),
                ('students', models.ManyToManyField(related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
