# Generated by Django 3.1.7 on 2021-05-28 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('creation_date', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('timer', models.SmallIntegerField(blank=True, default=360)),
                ('limit_of_tries', models.SmallIntegerField(blank=True, default=1)),
                ('visible_valid_answers', models.BooleanField(blank=True, default=False)),
                ('tag_name', models.CharField(default='', max_length=32)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultsPassing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.JSONField(blank=True, null=True)),
                ('used_time', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uchebnik.exercise')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=128)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uchebnik.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type', models.CharField(choices=[('radio', 'Переключатель.'), ('checkbox', 'Флажок.'), ('textbox', 'Ввод.')], max_length=16)),
                ('score', models.SmallIntegerField(blank=True, default=1, null=True)),
                ('answer_text', models.CharField(blank=True, max_length=32)),
                ('is_valid', models.BooleanField(default=False)),
                ('answer_input', models.CharField(blank=True, max_length=32)),
                ('valid_input', models.CharField(blank=True, default='', max_length=32)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uchebnik.question')),
            ],
        ),
    ]
